ignored_colors = []
allowed_colors = ["BE0039","FF4500","FFA800","FFD635","00A368","00CC78","7EED56","00756F","009EAA","2450A4","3690EA","51E9F4","493AC1","6A5CFF","811E9F","B44AC0","FF3881","FF99AA","6D482F","9C6926","000000","898D90","D4D7D9","FFFFFF"]
width = 2500
height = 2000
add-x = 1500
add-y = 1000
default_prio = 120

[[structure]]
name = "tumtud"
file = "tum-tudortmund-exzellenz.png"
disabled = false
startx = -331
starty = -76
priority = 127

[[structure]]
name = "tum-pinguin"
file = "tum-pinguin.png"
disabled = false
startx = -223
starty = -76
priority = 127

[[structure]]
name = "BO"
file = "BO.png"
disabled = false
startx = -205
starty = -75
priority = 126

[[structure]]
name = "it"
file = "it.png"
disabled = false
startx = -231
starty = -65
priority = 126